# Generated by Django 4.2.17 on 2025-01-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='departmentId',
        ),
    ]
