# Generated by Django 4.2.17 on 2025-01-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_rename_department_employee_departmentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departmentId',
            new_name='department',
        ),
    ]
